language: swift
osx_image: xcode10.1
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
  - pod repo update
  - pod lib lint --fail-fast --verbose
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - nilit.danan@kaltura.com
      - gilad.nadav@kaltura.com
    on_success: change
    on_failure: always
