language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
  - cd Example
  - pod update
  - xcodebuild -scheme NetKit-Example -workspace NetKit.xcworkspace -sdk iphonesimulator
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - vadim.kononov@kaltura.com
    on_success: change
    on_failure: change
