language: objective-c
osx_image: xcode8.1
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
  - cd Example
  - pod update
  - xcodebuild -scheme NetKit-Example -workspace NetKit.xcworkspace
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - rivka.peleg@kaltura.com
      - ziv.hundert@kaltura.com
    on_success: change
    on_failure: always
